spring:
  application:
    name: E-comm

  datasource:
    url: jdbc:mysql://localhost:3306/ecom_db
    username: root
    password: Az2003=Me#21

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
